image: lightspot21/acubesat-ci:latest

stages:
  - build

before_script:
  - g++ --version
  - cat /etc/*-release

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GCC_COLORS: "error=31;1:warning=35;1:note=36;1:range1=32:range2=34:locus=39;1:quote=39;1:fixit-insert=32:fixit-delete=31:diff-filename=39;1:diff-hunk=32:diff-delete=31:diff-insert=32:type-diff=32;1"
    CLICOLOR_FORCE: 1 # Necessary for cmake to output colours
  script:
    - cmake . -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
    - make -j4
    - make clean
    - cmake . -DCMAKE_CXX_FLAGS="-Wall -Wextra -fdiagnostics-color=always" # Build again, but with more warnings
    - make -j4
